replicaCount: 1

los_namespace: "los"

los:
  image:
    repository: willnilges/meshdb-line-of-sight
    tag: helm
    pullPolicy: Always
  port: 3000

los_backend:
  image:
    repository: andrewdickinson/meshdb-los-tool
    tag: latest
    pullPolicy: Always
  port: 3000

los_database:
  image:
    repository: postgis/postgis
    tag: latest
    pullPolicy: Always
  port: 5432
  db_name: los
  pvc_name: "los-postgis-pvc"
  pvc_size: "3Gi"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
