los_namespace: "los"

los:
  image:
    repository: willnilges/meshdb-line-of-sight
    tag: helm
    pullPolicy: Always
  port: 3000
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 128Mi
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  nodeSelector: {}
  affinity: {}
  tolerations: []

los_backend:
  image:
    repository: andrewdickinson/meshdb-los-tool
    tag: latest
    pullPolicy: Always
  port: 3000
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 128Mi
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http
  nodeSelector: {}
  affinity: {}
  tolerations: []

los_database:
  image:
    repository: postgis/postgis
    tag: 16-master
    pullPolicy: Always
  port: 5432
  db_name: los
  pvc_name: "los-postgis-pvc"
  pvc_size: "3Gi"
  resources:
    limits:
      cpu: 512m
      memory: 512Mi
    requests:
      cpu: 64m
      memory: 256Mi
  nodeSelector: {}
  affinity: {}
  tolerations: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}
