apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "los.fullname" . }}-backend
  namespace: {{ .Values.los_namespace }}
  labels:
    {{- include "los.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "los.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: los-backend
        {{- include "los.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.los_backend.image.repository }}:{{ .Values.los_backend.image.tag }}"
          imagePullPolicy: {{ .Values.los_backend.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: database-url
            - name: LOS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: los-database-url
          ports:
            - name: http
              containerPort: {{ .Values.los_backend.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
