apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "los.fullname" . }}-backend
  namespace: {{ .Values.los_namespace }}
  labels:
    {{- include "los.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "los.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: los-backend
        {{- include "los.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imageCredentials }}
      imagePullSecrets:
        - name: pull-secret
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.los_backend.image.repository }}:{{ .Values.los_backend.image.tag }}"
          imagePullPolicy: {{ .Values.los_backend.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: backend-secrets
          ports:
            - name: http
              containerPort: {{ .Values.los_backend.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.los_backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.los_backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.los_backend.resources | nindent 12 }}
      {{- with .Values.los_backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.los_backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.los_backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
