apiVersion: v1
kind: Service
metadata:
  name: {{ include "los.fullname" . }}-backend
  namespace: {{ .Values.los_namespace }}
  labels:
    {{- include "los.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.los_backend.port }}
      targetPort: {{ .Values.los_backend.port }}
      protocol: TCP
      name: http
  selector:
    app: los-backend
