apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "los.fullname" . }}-backend
  namespace: {{ .Values.los_namespace }}
  labels:
    {{- include "los.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.los_backend.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "los.fullname" . }}-backend
                port:
                  number: {{ .Values.los_backend.port }}
