apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.los_namespace }}
type: Opaque
data:
  database-url: {{ .Values.backend.database_url | b64enc | quote }}
  los-database-url: {{ .Values.backend.los_database_url | b64enc | quote }}
  database-user: {{ .Values.backend.database_user | b64enc | quote }}
  database-password: {{ .Values.backend.database_password | b64enc | quote }}
