apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.los_namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.backend.database_url | b64enc | quote }}
  LOS_DATABASE_URL: {{ .Values.backend.los_database_url | b64enc | quote }}
