apiVersion: v1
kind: Secret
metadata:
  name: los-secrets
  namespace: {{ .Values.los_namespace }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.backend.database_user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.database_password | b64enc | quote }}
